name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    
    permissions:
      pages: write
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2.5.0
      
      - name: Build
        run: | 
          cargo run
          touch site/.nojekyll

      - name: Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          force_orphan: true
