name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2.5.0

      - run: cargo run
      - run: touch site/.nojekyll

      - uses: actions/upload-pages-artifact@v1.0.9
        with:
          path: site

  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}

    needs: build

    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
